### ISSUE TITLE
Crash in connection.coffee when restarting Tapchat

### ISSUE THREAD

**Issue by cwc** [tapchat/tapchat#26]
After successfully using Tapchat for a bit, I needed to restart it. It immediately crashes in [connection.coffee](https://github.com/codebutler/tapchat/blob/ab2d45c6d30a028ca9d2ad18f19c61913784872d/src/tapchat/connection.coffee#L401) with this log output:

```
2014-02-09T17:27:17.316Z - warn: Certificate needs manual trust: DEPTH_ZERO_SELF_SIGNED_CERT

/home/ubuntu/apps/tapchat/src/tapchat/connection.coffee:401
      unless member = buffer.getMember(to)
                     ^
TypeError: Object #<ConversationBuffer> has no method 'getMember'
    at Connection.signalHandlers.+mode (/home/ubuntu/apps/tapchat/src/tapchat/connection.coffee:401:22)
    at handler (/home/ubuntu/apps/tapchat/src/tapchat/connection.coffee:321:12)
    at /home/ubuntu/apps/tapchat/src/tapchat/connection.coffee:328:12
    at nextTickWorker (/home/ubuntu/apps/tapchat/node_modules/capisce/lib/capisce.js:40:28)
    at process._tickCallback (node.js:415:13)
    at process._tickFromSpinner (node.js:390:15)
```

**Comment by mpontes** [comment]
Just got the same today, Tapchat crashed with that stack trace and would crash again on restart. Had to delete .tapchat and start from scratch to get past it.

**Comment by Redth** [comment]
Getting this every week or two as well... I had to delete the whole ~/.tapchat/ and start over with my config which is a real big pain...

**Comment by kmdm** [comment]
Seems to be caused by a user mode, e.g. /mode mynick +w, (badly?) fixed with:-

```
$ git diff src/tapchat/connection.coffee
diff --git a/src/tapchat/connection.coffee b/src/tapchat/connection.coffee
index 71cb99f..fe97792 100644
--- a/src/tapchat/connection.coffee
+++ b/src/tapchat/connection.coffee
@@ -398,6 +398,9 @@ class Connection extends EventEmitter
       unless buffer = @getBuffer(channel)
         return over()

+      if not (buffer instanceof ChannelBuffer)
+        return over()
+
       unless member = buffer.getMember(to)
         return over()

@@ -421,6 +424,9 @@ class Connection extends EventEmitter
       unless buffer = @getBuffer(channel)
         return over()

+      if not (buffer instanceof ChannelBuffer)
+        return over()
+
       unless member = buffer.getMember(to)
         return over()
```

Then: `coffee --map -c -o lib src`
