### ISSUE TITLE
Error: listen EAFNOSUPPORT

### ISSUE THREAD

**Issue by againtoday** [tapchat/tapchat#32]
Hello codebutler!!

After a few seconds tapchat crashes on my raspbian, the former version worked ok with node 0.8.x.

$ node ./tapchat start -v -f
##### 

connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Error: listen EAFNOSUPPORT
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1020:19)
    at listen (net.js:1061:10)
    at net.js:1143:9
    at dns.js:72:18
    at process._tickCallback (node.js:415:13)
    at process._tickFromSpinner (node.js:390:15)
###### 

Software:
- node v0.10.25 (npm 1.3.24) compiled from source, but i tried v0.10.24 and v0.10.26 too with same results.
- last version available at github, and npm version too
- Raspbian GNU/Linux 7 (with ipv6 disabled)

Thanks :-)

**Comment by codebutler** [comment]
Hm, this is probably because IPv6 is disabled.

**Comment by mpontes** [comment]
Getting issues on FreeBSD most likely caused by the same source as this. On FreeBSD, I need to set the sysctl net.inet6.ip6.v6only to 0 in order for IPv6 sockets to accept IPv4 connections, which isn't the default and not recommended, apparently.

Regardless of that setting, I'm also unable to start the new Tapchat server on a jail with only IPv4 addresses, it errors out and exits at the beginning:

```
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Error: listen Unknown system errno 43
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1020:19)
    at listen (net.js:1061:10)
    at net.js:1135:9
    at dns.js:72:18
    at process._tickCallback (node.js:415:13)
    at process._tickFromSpinner (node.js:390:15)
```

(43 is EPROTONOSUPPORT as defined in sys/errno.h, node probably doesn't like FreeBSD errnos)

**Comment by aliceinwire** [comment]
i have same error :/
we cannot use just ipv4 for use tapchat?
