### ISSUE TITLE
The server crashes about once a day when sending a push notification.

### ISSUE THREAD

**Issue by sangh** [tapchat/tapchat#4]
I get this randomly:

/usr/lib/node_modules/tapchat/lib/tapchat/push_client.js:57
        if (!response.statusCode.toString().match(/^2/)) {

TypeError: Cannot read property 'statusCode' of undefined
    at Request.PushClient.sendPush [as _callback](/usr/lib/node_modules/tapchat/lib/tapchat/push_client.js:57:22)
    at Request.init.self.callback (/usr/lib/node_modules/tapchat/node_modules/request/main.js:119:22)
    at Request.EventEmitter.emit (events.js:88:17)
    at ClientRequest.Request.init.self.clientErrorHandler (/usr/lib/node_modules/tapchat/node_modules/request/main.js:207:10)
    at ClientRequest.EventEmitter.emit (events.js:88:17)
    at CleartextStream.socketErrorListener (http.js:1330:9)
    at CleartextStream.EventEmitter.emit (events.js:88:17)
    at Socket.onerror (tls.js:1296:17)
    at Socket.EventEmitter.emit (events.js:115:20)
    at Socket.connect.require.lookup.addressType (net.js:697:16)

I think it should be as easy as changing lines 57-59 from:

```
if (!response.statusCode.toString().match(/^2/)) {
  Log.error("Error sending push notification: " + response.statusCode);
}
```

To:

```
if (typeof(response) === 'undefined') {
    Log.error("Error sending push notification, response undefined.");
} else if (!response.statusCode.toString().match(/^2/)) {
    Log.error("Error sending push notification: " + response.statusCode);
}
```

Am I wrong?

**Comment by codebutler** [comment]
This is fixed in dea971b7e62f754f6d26fe5c50064d1cbf07bbe5 and will be included in the next release.
