### ISSUE TITLE
Object #<ConversationBuffer> has no method 'getMember'

### ISSUE THREAD

**Issue by kaizoku** [tapchat/tapchat#64]
tapchat fails on start

```
kaizoku@dicerion tapchat % git log|head -n1
commit 249e81c3c50a8a96bd8a34612fe145889881ad4e
kaizoku@dicerion tapchat % ./bin/tapchat start -f
body-parser deprecated bodyParser: use individual json/urlencoded middlewares lib/tapchat/engine.js:131:20
body-parser deprecated undefined extended: provide extended option node_modules/body-parser/index.js:74:29

TapChat ready at https://localhost:8067


/home/kaizoku/src/tapchat/src/tapchat/connection.coffee:401
      unless member = buffer.getMember(to)
                             ^
TypeError: Object #<ConversationBuffer> has no method 'getMember'
    at Connection.signalHandlers.+mode (/home/kaizoku/src/tapchat/src/tapchat/connection.coffee:401:30)
    at Connection.addEventListeners._results.push._this.client.addListener.handler (/home/kaizoku/src/tapchat/src/tapchat/connection.coffee:321:27)
    at Connection.addEventListeners (/home/kaizoku/src/tapchat/src/tapchat/connection.coffee:328:13)
    at nextTickWorker (/home/kaizoku/src/tapchat/node_modules/capisce/lib/capisce.js:40:28)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

**Comment by kaizoku** [comment]
I tried the newer 0.10.x release of node and it works fine.
I guess this code just doesn't work on 0.8.x.

**Comment by kaizoku** [comment]
Looks like that only hid the problem? Still happening with 0.10.31.

```
kaizoku@dicerion tapchat % ~/src/node-v0.10.31/out/Release/node bin/tapchat start -f
body-parser deprecated bodyParser: use individual json/urlencoded middlewares lib/tapchat/engine.js:131:20
body-parser deprecated undefined extended: provide extended option node_modules/body-parser/index.js:74:29


TapChat ready at https://localhost:8067


/home/kaizoku/src/tapchat/src/tapchat/connection.coffee:401
      unless member = buffer.getMember(to)
                             ^
TypeError: Object #<ConversationBuffer> has no method 'getMember'
    at Connection.signalHandlers.+mode (/home/kaizoku/src/tapchat/src/tapchat/connection.coffee:401:30)
    at handler (/home/kaizoku/src/tapchat/src/tapchat/connection.coffee:321:27)
    at /home/kaizoku/src/tapchat/src/tapchat/connection.coffee:328:13
    at nextTickWorker (/home/kaizoku/src/tapchat/node_modules/capisce/lib/capisce.js:40:28)
    at process._tickCallback (node.js:419:13)
```

**Comment by athalean** [comment]
Can confirm that this happens:

```
athalean@starlight:~/tapchat$ bin/tapchat start -f
body-parser deprecated bodyParser: use individual json/urlencoded middlewares lib/tapchat/engine.js:131:20
body-parser deprecated undefined extended: provide extended option node_modules/body-parser/index.js:74:29

TapChat ready at https://localhost:*****


/home/athalean/tapchat/src/tapchat/connection.coffee:401
      unless member = buffer.getMember(to)
                             ^
TypeError: Object #<ConversationBuffer> has no method 'getMember'
    at Connection.signalHandlers.+mode (/home/athalean/tapchat/src/tapchat/connection.coffee:401:30)
    at handler (/home/athalean/tapchat/src/tapchat/connection.coffee:321:27)
    at /home/athalean/tapchat/src/tapchat/connection.coffee:328:13
    at nextTickWorker (/home/athalean/tapchat/node_modules/capisce/lib/capisce.js:40:28)
    at process._tickCallback (node.js:419:13)
```

**Comment by ghost** [comment]
I believe this is the same issue I was seeing.  It seemed to be related to usermodes.  Removing all my usermodes caused the crashes to stop.

**Comment by tjb0607** [comment]
This happens to me whenever I try to connect to my ZNC bouncer, making TapChat completely unusable.

http://tjb0607.me/image/tapchatcrash.png

**Comment by kmdm** [comment]
There's a patch in an existing issue that fixes it for me:-

https://github.com/tapchat/tapchat/issues/26
