### ISSUE TITLE
crash on user mode after connection

### ISSUE THREAD

**Issue by ghost** [tapchat/tapchat#66]
Every time I start tapchat, it connects to my znc server and immediately crashes after connecting:

/home/tapchat/git/tapchat/src/tapchat/connection.coffee:401
      unless member = buffer.getMember(to)
                             ^
TypeError: Object #<ConversationBuffer> has no method 'getMember'
    at Connection.signalHandlers.+mode (/home/tapchat/git/tapchat/src/tapchat/connection.coffee:401:30)
    at handler (/home/tapchat/git/tapchat/src/tapchat/connection.coffee:321:27)
    at /home/tapchat/git/tapchat/src/tapchat/connection.coffee:328:13
    at nextTickWorker (/home/tapchat/git/tapchat/node_modules/capisce/lib/capisce.js:40:28)  
    at process._tickCallback (node.js:419:13)

It seems to be related to znc sending the user mode immediately after the motd completes, I see just befores the crash:

....           Try us on IPv6 at irc.choopa.net\n-              (2001:19f0::dead:beef:cafe)\n-  \nEnd of /MOTD command.\n"}
2014-09-19T05:11:07.080Z - silly: IRC RECV [Efnet]: :me!me@me.com MODE me :+i

If I unset my +i, the crash doesn't occur.

**Comment by kmdm** [comment]
I just posted a simple patch for this in #26

**Comment by ghost** [comment]
Thanks, this does look like a dup of #26
